### ISSUE TITLE
Error in segment tree beats implementation

### ISSUE THREAD

**Issue by peltorator** [kmyk/competitive-programming-library#10]
[Here](https://github.com/kmyk/competitive-programming-library/blob/a15a7e3fa34bdd94c1ea98c9faf6a86a93d60537/data_structure/segment_tree_beats.hpp#L172) you add `g` to `lazy_add` and `lazy_update`. But [here](https://github.com/kmyk/competitive-programming-library/blob/master/data_structure/segment_tree_beats.hpp#L192) you first apply `update` and then `add`. So you'll add `g` twice. I think you just need to delete lines 171-173

**Comment by kmyk** [comment]
It seems correct with the current implementation because:
1. in the `pushdown` method, [it `return`s from the method and doesn't `add` after applying `update`](https://github.com/kmyk/competitive-programming-library/blob/a15a7e3fa34bdd94c1ea98c9faf6a86a93d60537/data_structure/segment_tree_beats.hpp#L197), and
2. deleting lines 171-173 makes the tests using [DSL_2_G](http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=DSL_2_G) and [DSL_2_H](http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=DSL_2_H) fail.

However, anyway, thank you for telling me a possible bug!
